basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a REST API for the Executive eCommerce platform.
  title: Executive API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
